### PR TITLE
downgrade webex

### PR DESCRIPTION
**Pull request by jeremywillans**
Downgrade `webex` to exact-version 2.4.2 due to reported issues with the Framework.

### CODE REVIEW

**Comment by jeremywillans** [comment]
@jpjpjp - for your review and approval

**Comment by jpjpjp** [comment]
LGTM.   One question.  How did you determine that 2.4.2 was the right version?   Are you certain that this version supports the fedramp option that you added into the framework recently?   Assuming so this is approved (if I can figure out how to approve on mobile!$

**Review by jpjpjp — APPROVED** [review]

**Comment by jeremywillans** [comment]
> 

2.4.2 fixes the Logger Proxy issue.
1.156 is where FedRamp support was introduced.

**Comment by jpjpjp** [comment]
@jeremywillans thanks for checking that.   I updated the version number in version-history.mc.   I think this is good to commit!

**Pull request merged**
