### PR TITLE
feat(framework): update footer to current repo

### PR DESCRIPTION
**Pull request by adamweeks**

### CODE REVIEW

**Comment by jeremywillans** [comment]
@adamweeks can you please update L7 in installation.md and then regenerate the README file (using build.sh)

**Comment by jpjpjp** [comment]
I can include this in my next PR where I'll finally add that feature that @adamweeks asked for.

**Comment by jpjpjp** [comment]
Incorporated in this PR [Fix mongo warning](https://github.com/WebexCommunity/webex-node-bot-framework/pull/93)

**Comment by adamweeks** [comment]
Thanks @jpjpjp

**Pull request closed without merging**
